### ISSUE TITLE
Null reference for unpublished content

### ISSUE THREAD

**Issue by vsosinga** [christopherrobinson/Virtual-Nodes-for-Umbraco-8#1]
Hi,

thanks for creating the plugin first of all. I ran into a bug however:
When running in preview mode (either via the backoffice of through the UMB_PREVIEW cookie), non-published items also get included and since they do not have a URL yet the plugin fails on all pages that are under a virtual node:
![image](https://user-images.githubusercontent.com/38254373/63272413-47650400-c29c-11e9-8cec-a9df9195b9eb.png)

Umbraco version: 8.1.1

### Steps to reproduce

1. Create a virtual node
2. Create an unpublished item under the virtual node and preview it

**Comment by AndyVokurka** [comment]
i do happen to have the same problem. is it possible to fix it somehow?

**Comment by amitch17** [comment]
+1 for this.  Package works nicely otherwise, unfortunately it breaks the view of the whole site (cos of the cookie) and freaks out the content editors!

Would you accept submissions if I dig into the code to try and fix it?

**Comment by christopherrobinson** [comment]
Fixed with the commit by @amitch17 👍

I'll upload an updated package to Our Umbraco this evening.
